# Custom openldap docker-compose for passbolt dev
services:
    openldap:
        container_name: ddev-${DDEV_SITENAME}-openldap
        image: osixia/openldap:latest
        command: --copy-service # needed to copy init file
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        #profiles:
        #    - ldap
        environment:
            VIRTUAL_HOST: $DDEV_HOSTNAME
            LDAP_LOG_LEVEL: "256"
            LDAP_ORGANISATION: "Example Inc."
            LDAP_DOMAIN: "example.org"
            LDAP_BASE_DN: ""
            LDAP_ADMIN_PASSWORD: "admin"
            LDAP_CONFIG_PASSWORD: "config"
            LDAP_READONLY_USER: "false"
            LDAP_RFC2307BIS_SCHEMA: "false"
            LDAP_BACKEND: "mdb"
            LDAP_TLS: "true"
            LDAP_TLS_CRT_FILENAME: "ldap.crt"
            LDAP_TLS_KEY_FILENAME: "ldap.key"
            LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
            LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
            LDAP_TLS_ENFORCE: "false"
            LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
            LDAP_TLS_VERIFY_CLIENT: "demand"
            LDAP_REPLICATION: "false"
            KEEP_EXISTING_CONFIG: "false"
            LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
            LDAP_SSL_HELPER_PREFIX: "ldap"

        volumes:
            - ldap_certificates:/container/service/slapd/assets/certs
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
        tty: true
        stdin_open: true
        external_links:
            - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
        ports:
            - 389
            - 636

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: ddev-${DDEV_SITENAME}-phpldapadmin
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        environment:
            HOSTNAME: $DDEV_HOSTNAME
            PHPLDAPADMIN_LDAP_HOSTS: ddev-${DDEV_SITENAME}-openldap
            PHPLDAPADMIN_HTTPS: false
            VIRTUAL_HOST: $DDEV_HOSTNAME
            HTTP_EXPOSE: 8076:80
            HTTPS_EXPOSE: 9103:80
        expose:
            - "80"
        depends_on:
            - openldap

volumes:
    ldap_certificates:
    ldap_data:
    ldap_config:
